[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[phases.install]
cmds = ["npm ci --include=dev", "cd frontend && npm ci --include=dev"]

[phases.build]
cmds = ["npm run build", "cd frontend && npm run build"]

[start]
cmd = "npm run start:prod"

# Make these environment variables available during build
[variables]
DATABASE_URL = "${{DATABASE_URL}}"
DIRECT_URL = "${{DIRECT_URL}}"
VITE_API_URL = "/api"
